version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev-docs

formats: all
