sudo: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7-dev"
    - "pypy"
    - "pypy3"
matrix:
    allow_failures:
        - python: "3.7-dev"
install:
    - travis_retry pip install -e ".[dev,placefinder,timezone]"
script:
    - coverage run -m py.test
    - coverage report
