sudo: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.6-dev"
    - "3.7-dev"
    - "nightly"
    - "pypy"
    - "pypy3"
install:
    # Coveralls 4.0 doesn't support Python 3.2
    - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; fi
    - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then travis_retry pip install coverage; fi
script:
    - pip install nose-cov requests-oauthlib pytz
    - nosetests --verbose --with-cover --cover-erase --cover-package=geopy
